# to get all countries, must return a list - you DON'T need the token here
GET http://localhost:8000/api/person

# to get a specific country, must return the complete data for the country with the given id - you DON'T need the token here
GET http://localhost:8000/api/person/1

# to create a new person
POST http://localhost:8000/api/person
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkJydW5vIEZlcm5hbmRvIEJldmlsYXF1YSIsInVzZXJuYW1lIjoiYmV2aWxhcXVhIiwiZW1haWwiOiJiYmJldmlsYXF1YUBnbWFpbC5jb20iLCJpYXQiOjE2MzcxMDQ1ODQsImV4cCI6MTYzNzEwOTU4NH0.Una1g98BRMQc49mXsZAhrEYwu0l-XuJi0GXoc9oPGvg

{
  "name": "Fabrício Certezas",
  "email": "fabriciocertezas@fabriciocertezas.com",
  "phone": "554999099938",
  "birth_date": "1980-07-03",
  "cpf": "103.411.729-79",
  "address": "Endereço teste teste",
  "city": "Concórdia",
  "state": "SC"
}

# to update the person with the given id
PUT http://localhost:8000/api/person/1
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkJydW5vIEZlcm5hbmRvIEJldmlsYXF1YSIsInVzZXJuYW1lIjoiYmV2aWxhcXVhIiwiZW1haWwiOiJiYmJldmlsYXF1YUBnbWFpbC5jb20iLCJpYXQiOjE2MzcxMDQ1ODQsImV4cCI6MTYzNzEwOTU4NH0.Una1g98BRMQc49mXsZAhrEYwu0l-XuJi0GXoc9oPGvg

{
  "name": "Bruno Fernando Bevilaqua",
  "email": "bbbevilaqua@gmail.com",
  "phone": "5549998320023",
  "birth_date": "2000-03-05",
  "cpf": "103.411.729-79",
  "address": "",
  "city": "",
  "state": ""
}

# to delete the person with the given id
DELETE http://localhost:8000/api/person/4
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkJydW5vIEZlcm5hbmRvIEJldmlsYXF1YSIsInVzZXJuYW1lIjoiYmV2aWxhcXVhIiwiZW1haWwiOiJiYmJldmlsYXF1YUBnbWFpbC5jb20iLCJpYXQiOjE2MzY4NTg0MjMsImV4cCI6MTYzNjg2MzQyM30.fikvW5AJgm0nWTN8l2RLkAhFZSscVcCjfou8hwOZ5mo
