# to get all countries, must return a list - you DON'T need the token here
GET http://localhost:8000/api/person

# to get a specific country, must return the complete data for the country with the given id - you DON'T need the token here
GET http://localhost:8000/api/person/<personId>

# to create a new person
POST http://localhost:8000/api/person
Content-Type: application/json
x-access-token: <token>

{
  "name": "Fabrício Certezas",
  "email": "fabriciocertezas@fabriciocertezas.com",
  "phone": "554999099938",
  "birth_date": "1980-07-03",
  "cpf": "103.411.729-79",
  "address": "Endereço teste teste",
  "city": "Concórdia",
  "state": "SC"
}

# to update the person with the given id
PUT http://localhost:8000/api/person/<personId>
Content-Type: application/json
x-access-token: <token>

{
  "name": "Bruno Fernando Bevilaqua",
  "email": "bbbevilaqua@gmail.com",
  "phone": "5549998320023",
  "birth_date": "2000-03-05",
  "cpf": "103.411.729-79",
  "address": "",
  "city": "",
  "state": ""
}

# to delete the person with the given id
DELETE http://localhost:8000/api/person/<personId>
x-access-token: <token>
