# to get all users, must return a list
GET http://localhost:8000/api/user
x-access-token: <token>

# to get a specific user, must return the complete data for the user with the given id
GET http://localhost:8000/api/user/<userId>
x-access-token: <token>

# to create a new user
POST http://localhost:8000/api/user
Content-Type: application/json
x-access-token: <token>

{
  "name": "User Test",
  "username": "userteste",
  "email": "usertest@gmailsss.com",
  "password": "123",
  "passwordConfirm": "123"
}

# to update the user with the given id
PUT http://localhost:8000/api/user/2
Content-Type: application/json
x-access-token: <token>

{
  "name": "User Number two",
  "username": "user2",
  "email": "user2@gmail.com"
}

# to update the user's password with the given id
PUT http://localhost:8000/api/user/1/password
Content-Type: application/json
x-access-token: <token>

{
  "password": "123",
  "passwordConfirm": "123"
}

# to delete the user with the given id
DELETE http://localhost:8000/api/user/<userId>
x-access-token: <token>
